### ISSUE TITLE
make my compter crash 

### ISSUE THREAD

**Issue by robothax** [SeanPesce/Dark_Souls_Config_Utility#6]
EDIT: Troll

**Comment by SeanPesce** [comment]
Hi robothax, we'll need more information about your computer specs and usage of the program if we want to fix this issue. What were you doing with the program when it crashed? Keep in mind that a crash could have been due to one of the included Dark Souls mods, in which case you would have to contact the developer of the mod that caused your issue.

**Comment by robothax** [comment]
nvm fixed it
